---
title: "RWorksheet_Doronila#2.R"
author: "Jocedel Garnette Doronila"
date: "2023-12-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
vector_a <- -5:5
vector_a
x <- 1:7
x
vector_b <- seq(1, 3, by = 0.2)
vector_b
ages <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27, 22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35, 24, 33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26, 18)
ages
ages_a <- ages[3]
ages_a
ages_b <- ages[c(2, 4)]
ages_b
ages_c <- ages[-c(4, 12)]
ages_c
names <- c("first" = 3, "second" = 0, "third" = 9)
names
names_a <- names[c("first", "third")]
names_a
x_2 <- -3:2
x_2[2] <- 0
x_2
diesel_purchase <- data.frame(
  Month = c("Jan", "Feb", "March", "Apr", "May", "June"),
  Price_Per_Liter_PHP = c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00),
  Purchase_Quantity_Liter = c(25, 30, 40, 50, 10, 45)
)
diesel_purchase
average_fuel <- weighted.mean(diesel_purchase$Price_Per_Liter_PHP, diesel_purchase$Purchase_Quantity_Liter)
average_fuel
rivers 
length_rivers <- length(rivers)
sum_rivers <- sum(rivers)
mean_rivers <- mean(rivers)
median_rivers <- median(rivers)
var_rivers <- var(rivers)
sd_rivers <- sd(rivers)
min_rivers <- min(rivers)
max_rivers <- max(rivers)
river_data <- c(length_rivers, sum_rivers, mean_rivers, median_rivers, var_rivers, sd_rivers, min_rivers, max_rivers)
river_data
Forbes_Ranking <- data.frame(
  Power_Ranking = 1:25,
  Celebrity_Name = c(
    "Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods",
    "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos",
    "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali",
    "Paul McCartney", "George Lucas", "Elton John", "David Letterman",
    "Phil Mickelson", "J.K. Rowling", "Brad Pitt", "Peter Jackson",
    "Dr. Phil McGraw", "Jay Leno", "Celine Dion", "Kobe Bryant"
  ),
  Pay = c(
    67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40,
    47, 75, 25, 39, 45, 32, 40, 31
  )
)
Forbes_Ranking$Power_Ranking[Forbes_Ranking$Celebrity_Name == "J.K. Rowling"] <- 15
Forbes_Ranking$Pay[Forbes_Ranking$Celebrity_Name == "J.K. Rowling"] <- 90
Forbes_Ranking

write.csv(Forbes_Ranking, file = "PowerRanking.csv", row.names = FALSE)

print("CSV file 'PowerRanking.csv' has been saved.")

excel <- read.csv("PowerRanking.csv")

print(excel)

selected_rows <- Forbes_Ranking[10:20, ]

save(selected_rows, file = "Ranks.RData")

print("RData file 'Ranks.RData' has been saved.")

load("Ranks.RData")

print(selected_rows)

# E. The specific output will include the values in columns "Power_Ranking," "Celebrity_Name," and "Pay" for the selected rows. It will provide insights into the modified data for the specified range of rows.

library(readr)
hotels_vienna <- read_csv("hotels-vienna.xlsx.csv")
dim(hotels_vienna)
selected_columns <- hotels_vienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
save(selected_columns, file = "new.RData")
load("new.RData")
head(selected_columns)
tail(selected_columns)

vegetables <- c("Carrot", "Broccoli", "Spinach", "Tomato", "Cucumber", "Bell Pepper", "Zucchini", "Lettuce", "Cabbage", "Onion")

print(vegetables)

vegetables <- c(vegetables, "Kale", "Eggplant")

print(vegetables)

vegetables <- append(vegetables, c("Radish", "Artichoke", "Asparagus", "Cauliflower"), after = 5)

print(vegetables)

length(vegetables)

vegetables <- vegetables[-c(5, 10, 15)]

print(vegetables)

length(vegetables)

```